package leetcode;

public enum Algorithm {
    IN_ORDER_TRAVERSAL,
    LEVEL_ORDER_TRAVERSAL,
    BREADTH_FIRST_SEARCH,
    DEPTH_FIRST_SEARCH,
    SORTING,
    BINARY_SEARCH,
    BINARY_TREE_MORRIS_TRAVERSAL,
    QUICK_SELECT,
    DYNAMIC_PROGRAMMING,
    SLIDING_WINDOW,
    TWO_POINTERS;
}
