package leetcode;

public enum Algorithm {
    BIT_MASK,
    SIMULATION,
    MERGE_INTERVAL,
    MATH,
    PREFIX_SUM,
    INDEXING,
    IN_ORDER_TRAVERSAL,
    LEVEL_ORDER_TRAVERSAL,
    BREADTH_FIRST_SEARCH,
    DEPTH_FIRST_SEARCH,
    DIVIDE_AND_CONQUER,
    SIEVE_OF_ERATOSTHENES,
    SORTING,
    PATIENCE_SORTING,
    BINARY_SEARCH,
    BINARY_TREE_MORRIS_TRAVERSAL,
    QUICK_SELECT,
    DYNAMIC_PROGRAMMING,
    SLIDING_WINDOW,
    TWO_POINTERS,
    FENWICK_TREE,
    MONOTONIC_QUEUE;
}
